name: Python CI

on:
  push:
    branches: [main, log-pytest]
  pull_request:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres-db:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: geo_project_db
          POSTGRES_HOST: postgres-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Chekout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest